[package]
name = "jandering_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.14", features = ["derive"] }
env_logger = "0.10"
cgmath = { git = "https://github.com/rustgd/cgmath.git", version = "0.18.0", features = ["bytemuck"] }
log = "0.4"
pollster = "0.3.0"
wgpu = "0.18"
winit = "0.28"
cfg-if = "1.0.0"
web-time = "1.0.0"
image = {version = "0.24.8", features = ["png", "jpeg"], default-features = false}
reqwest = "0.11.24"
anyhow = "1.0.79"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = {verison = "0.18", features = ["webgl"]}
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Location",
]}
